// Constantes y keywords (portado del Módulo 2 del notebook original).

export const COLUMN_DISPLAY_NAMES = [
  "ID",
  "Proceso",
  "Eje",
  "Tema",
  "Nombre",
  "Cobertura",
  "Periodicidad",
  "Liga Web",
  "Fuente",
  "Año",
  "Estado",
  "Valor"
];

export const EXPECTED_COLUMNS = [
  "id",
  "proceso",
  "eje",
  "tema",
  "nombre",
  "cobertura",
  "periodicidad",
  "liga_web",
  "fuente",
  "año",
  "estado",
  "valor"
];

export const DYNAMIC_OPTIONS_COLUMNS = [
  "proceso",
  "eje",
  "tema",
  "cobertura",
  "periodicidad",
  "estado"
];

export const CODIGO_ESTADO_A_NOMBRE = {
  "01": "Aguascalientes",
  "02": "Baja California",
  "03": "Baja California Sur",
  "04": "Campeche",
  "05": "Coahuila de Zaragoza",
  "06": "Colima",
  "07": "Chiapas",
  "08": "Chihuahua",
  "09": "Ciudad de México",
  "10": "Durango",
  "11": "Guanajuato",
  "12": "Guerrero",
  "13": "Hidalgo",
  "14": "Jalisco",
  "15": "México",
  "16": "Michoacán de Ocampo",
  "17": "Morelos",
  "18": "Nayarit",
  "19": "Nuevo León",
  "20": "Oaxaca",
  "21": "Puebla",
  "22": "Querétaro",
  "23": "Quintana Roo",
  "24": "San Luis Potosí",
  "25": "Sinaloa",
  "26": "Sonora",
  "27": "Tabasco",
  "28": "Tamaulipas",
  "29": "Tlaxcala",
  "30": "Veracruz de Ignacio de la Llave",
  "31": "Yucatán",
  "32": "Zacatecas"
};

export const KEYWORDS = {
  "proceso": {
    "A. Prevención": [
      "existencia",
      "mecanismos",
      "cobertura",
      "plan",
      "programa",
      "profesionalización",
      "capacitación",
      "servicio civil",
      "reglas",
      "lineamientos",
      "diseño",
      "atributos",
      "calidad",
      "indicadores",
      "objetivos",
      "metas",
      "participación ciudadana",
      "contraloría social",
      "educación",
      "campañas",
      "comunicaciones",
      "código de ética",
      "declaración patrimonial",
      "evaluación de control y confianza",
      "personal",
      "recursos humanos"
    ],
    "B. Detección": [
      "percibe",
      "percepción",
      "frecuencia",
      "prevalencia",
      "incidencia",
      "experimentaron",
      "usuarios",
      "unidades económicas",
      "denuncias recibidas",
      "carpetas de investigación",
      "averiguaciones previas",
      "quejas recibidas",
      "actos de corrupción reportados",
      "conocimiento por terceros",
      "inconformidades",
      "observaciones",
      "investigación iniciada",
      "víctimas",
      "imputados",
      "inculpados",
      "causas penales ingresadas"
    ],
    "C. Sanción": [
      "sanciones",
      "condenatorias",
      "absolutorias",
      "multas",
      "inhabilitación",
      "destitución",
      "amonestación",
      "resarcitoria",
      "pliego de observaciones",
      "procedimientos de responsabilidad",
      "sentencias",
      "fincamiento",
      "sanciones económicas",
      "revocación",
      "castigo",
      "ejecución de sentencia",
      "cumplimiento de órdenes"
    ],
    "D. Fiscalización y control de recursos": [
      "auditoría",
      "fiscalización",
      "control interno",
      "observaciones",
      "presupuesto",
      "recursos",
      "contratos",
      "monto",
      "donativos",
      "compras",
      "obra pública",
      "licitaciones",
      "convocatorias",
      "adjudicaciones",
      "proveedores",
      "contratistas",
      "cuenta pública",
      "armonización contable",
      "estado de situación financiera",
      "ingresos",
      "egresos",
      "fideicomisos"
    ]
  },
  "eje": {
    "1. Combatir la corrupción y la impunidad": [
      "quejas",
      "denuncias",
      "faltas administrativas",
      "justicia",
      "delitos",
      "cohecho",
      "peculado",
      "enriquecimiento",
      "abuso de autoridad",
      "ejercicio indebido",
      "procuración",
      "impartición",
      "ministerio público",
      "causas penales",
      "sentencias",
      "sanciones",
      "responsabilidad administrativa",
      "investigación de servidores",
      "tribunales",
      "jueces",
      "magistrados",
      "fiscalía",
      "averiguación previa",
      "carpeta de investigación"
    ],
    "2. Combatir la arbitrariedad y el abuso de poder": [
      "profesionalización",
      "servicio civil",
      "carrera",
      "capacitación",
      "evaluación de desempeño",
      "declaración patrimonial",
      "planes anticorrupción",
      "programas sociales",
      "procesos institucionales",
      "indicadores",
      "reglas de operación",
      "riesgos",
      "auditoría",
      "fiscalización",
      "control interno",
      "obra pública",
      "contrataciones",
      "adquisiciones",
      "arrendamientos",
      "proveedores",
      "contratistas",
      "testigos sociales",
      "planeación",
      "programación",
      "presupuestación",
      "seguimiento",
      "evaluación",
      "marco jurídico",
      "transparencia",
      "datos abiertos",
      "rendición de cuentas"
    ],
    "3. Promover la mejora de la gestión y los puntos de contacto gobierno-sociedad": [
      "trámites",
      "servicios públicos",
      "puntos de contacto",
      "ciudadanía",
      "iniciativa privada",
      "licitaciones",
      "convocatorias",
      "permisos",
      "pagos",
      "predial",
      "tenencia",
      "atención ciudadana",
      "solicitudes de información",
      "oficina de transparencia",
      "módulos de orientación",
      "infracciones",
      "licencias de conducir",
      "registro civil",
      "afiliación",
      "consulta médica",
      "inscripción escolar",
      "compras del gobierno",
      "contratación pública",
      "MIPYMES",
      "competencia económica",
      "prácticas monopólicas"
    ],
    "4. Involucrar a la sociedad y el sector privado": [
      "participación ciudadana",
      "contraloría social",
      "vigilancia",
      "colaboración",
      "cocreación",
      "educación",
      "campañas anticorrupción",
      "comunicación",
      "integridad empresarial",
      "código de ética",
      "compliance",
      "denuncias corporativas",
      "testigos sociales",
      "observadores",
      "organizaciones civiles",
      "ONG",
      "sindicatos",
      "medios de comunicación",
      "redes sociales",
      "parlamento abierto",
      "gobierno abierto",
      "consulta ciudadana",
      "presupuesto participativo"
    ]
  },
  "tema": {
    "1.1. Prevención, detección, denuncia, investigación, substanciación y sanción de faltas administrativas": [
      "quejas",
      "denuncias",
      "oficina de contraloría",
      "procedimientos de responsabilidad",
      "declaración patrimonial",
      "conflictos de interés",
      "sistema informático para quejas",
      "buzón de quejas",
      "atención ciudadana",
      "faltas administrativas",
      "sanciones administrativas",
      "amonestación",
      "suspensión",
      "destitución",
      "inhabilitación",
      "responsabilidad resarcitoria"
    ],
    "1.2. Procuración e impartición de justicia en materia de delitos por hechos de corrupción": [
      "delitos",
      "cohecho",
      "peculado",
      "enriquecimiento ilícito",
      "tráfico de influencias",
      "abuso de autoridad",
      "ejercicio indebido",
      "carpetas de investigación",
      "averiguaciones previas",
      "causas penales",
      "sentencias condenatorias",
      "sentencias absolutorias",
      "jueces",
      "magistrados",
      "ministerio público",
      "fiscalía",
      "imputados",
      "víctimas"
    ],
    "2.1. Profesionalización e integridad en el servicio público": [
      "servicio civil",
      "carrera",
      "capacitación",
      "evaluación de control y confianza",
      "desempeño",
      "competencias",
      "personal",
      "licenciatura",
      "recursos humanos",
      "profesionalización",
      "integridad",
      "código de ética",
      "declaración patrimonial",
      "evaluación de desempeño"
    ],
    "2.2. Procesos institucionales": [
      "plan anticorrupción",
      "programas sociales",
      "riesgos",
      "indicadores",
      "metas",
      "cobertura",
      "desempeño",
      "presupuesto",
      "reglas de operación",
      "lineamientos",
      "diseño",
      "calidad",
      "cumplimiento de metas",
      "cuadrante",
      "targeting",
      "instrumentos de medición",
      "panel de control",
      "seguimiento",
      "evaluación de diseño",
      "consistencia y resultados"
    ],
    "2.3. Auditoría y fiscalización": [
      "auditoría",
      "fiscalización",
      "control interno",
      "observaciones",
      "revisión",
      "órgano de control",
      "visitaduría",
      "entidad de fiscalización",
      "armonización contable",
      "ejercicio y control",
      "seguimiento",
      "evaluación",
      "indicadores de resultados",
      "marco jurídico",
      "planeación",
      "programación",
      "presupuestación"
    ],
    "3.1. Puntos de contacto gobierno-ciudadanía: trámites, servicios y programas públicos": [
      "trámites",
      "servicios",
      "solicitudes de información",
      "atención ciudadana",
      "pagos",
      "predial",
      "tenencia",
      "permisos",
      "construcción",
      "licencias",
      "usuarios",
      "confianza en información",
      "módulos de orientación",
      "oficina de transparencia",
      "solicitudes de acceso a la información",
      "datos abiertos",
      "quejas de servicios",
      "contacto con autoridades"
    ],
    "3.2. Puntos de contacto gobierno-iniciativa privada": [
      "contrataciones",
      "licitaciones",
      "obra pública",
      "proveedores",
      "contratistas",
      "MIPYMES",
      "testigos sociales",
      "convocatorias",
      "adquisiciones",
      "arrendamientos",
      "servicios relacionados",
      "prácticas monopólicas",
      "competencia",
      "registro de contratistas",
      "sistema electrónico de contrataciones",
      "invitación restringida",
      "adjudicación directa"
    ],
    "4.1. Participación ciudadana: vigilancia, colaboración y cocreación": [
      "contraloría social",
      "órganos de participación",
      "consulta ciudadana",
      "vigilancia",
      "presupuesto participativo",
      "parlamento abierto",
      "gobierno abierto",
      "mecanismos de participación",
      "comités de contraloría",
      "consejos ciudadanos",
      "rendición de cuentas",
      "espacios de participación"
    ],
    "4.2. Corresponsabilidad e integridad empresarial": [
      "empresa",
      "integridad",
      "código de ética",
      "compliance",
      "proveedores",
      "denuncias corporativas",
      "programa de integridad",
      "anticorrupción",
      "políticas de sobornos",
      "conflicto de intereses",
      "transparencia corporativa"
    ],
    "4.3. Educación y comunicación para el control de la corrupción": [
      "educación",
      "campañas",
      "conocimiento cívico",
      "estudiantes",
      "comunicación",
      "redes sociales",
      "medios de comunicación",
      "divulgación",
      "sensibilización",
      "normalización de la corrupción",
      "cultura de la legalidad",
      "formación"
    ]
  }
};

export const AGGREGATION_KEYWORDS = [
  "total",
  "totales",
  "suma",
  "sum"
];

export const DISAGGREGATION_KEYWORDS = [
  "autoridades o instituciones",
  "nombre de las instituciones",
  "institución",
  "instituciones",
  "nombre de institución",
  "tipo de autoridad",
  "autoridad o institución",
  "autoridades"
];

export const ESTADO_COLUMN_ALIASES = [
  "cve_ent",
  "cvegeo",
  "entidad",
  "estado",
  "estados"
];

